eureka:
  client:
    service-url:
	    defaultZone: http://eureka-dev.com:7001/eureka/
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: configclient
  profiles:
    active:
  	- dev
	  
